columns:
  - 'SeniorCitizen'
  - 'Tenure'
  - 'MonthlyCharges'
  - 'TotalCharges'
  - 'Gender_Female'
  - 'Gender_Male'
  - 'Partner_No'
  - 'Partner_Yes'
  - 'Dependents_No'
  - 'Dependents_Yes'
  - 'PhoneService_No'
  - 'PhoneService_Yes'
  - 'MultipleLines_No'
  - 'MultipleLines_Yes'
  - 'InternetService_DSL'
  - 'InternetService_Fiber optic'
  - 'InternetService_No'
  - 'OnlineSecurity_No'
  - 'OnlineSecurity_Yes'
  - 'OnlineBackup_No'
  - 'OnlineBackup_Yes'
  - 'DeviceProtection_No'
  - 'DeviceProtection_Yes'
  - 'TechSupport_No'
  - 'TechSupport_Yes'
  - 'StreamingTV_No'
  - 'StreamingTV_Yes'
  - 'StreamingMovies_No'
  - 'StreamingMovies_Yes'
  - 'Contract_Monthly'
  - 'Contract_One year'
  - 'Contract_Two year'
  - 'PaperlessBilling_No'
  - 'PaperlessBilling_Yes'
  - 'PaymentMethod_Bank transfer (automatic)'
  - 'PaymentMethod_Credit card (automatic)'
  - 'PaymentMethod_Manual'